#!/usr/bin/env python3
"""PDHD fork (by DUPLICATION; the PDVD script is untouched) of doc pdvd/42's
d42_make_ref_dqdx_045.py: the PDHD stopping-particle dQ/dx-vs-residual-range
reference json at E = 0.4959 kV/cm -- the tables the PRODUCTION config has carried since
2026-09-03 (cfg/pgrapher/experiment/protodunevd/particle_dataset.jsonnet, doc
pdvd/29).  Fork by duplication of pdvd/stm/make_pdvd_ref_dqdx.py, which wrote
the 0.44 kV/cm set that doc 25 sec 13.6 was graded against; that file and its
output pdvd/stm/pdvd_ref_dqdx.json are left untouched as the doc-25 record.

Self-gate: the 0.45 tables read from the ROOT file must equal the compiled
jsonnet before anything is written.  The 0.50 kV/cm comparison set is carried
under the *_E050 keys exactly as before.

Repro:
  cd /nfs/data/1/xqian/toolkit-dev/wcp-porting-img/pdhd
  python3 docs/scripts/d42_make_ref_dqdx.py   # writes stm/pdhd_ref_dqdx.json
"""
import json
import os
import subprocess
import sys

import numpy as np
import uproot

HERE = os.path.dirname(os.path.realpath(__file__))
PDHD = os.path.normpath(os.path.join(HERE, "..", ".."))              # wcp-porting-img/pdhd
TOP = os.path.normpath(os.path.join(PDHD, "..", ".."))               # wcp-porting-img/pdhd -> toolkit-dev
EL = os.path.join(TOP, "energy_loss", "pion_travel")
ROOT045 = os.path.join(EL, "stopping_ave_dQ_dx_pdhd0496.root")   # E = 0.4959 kV/cm
ROOT050 = None                                                    # no PDHD comparison field set
JSONNET = "pgrapher/experiment/pdhd/particle_dataset.jsonnet"
PARTS = {"muon": "MuonDeDx", "electron": "ElectronDeDx", "pion": "PionDeDx",
         "kaon": "KaonDeDx", "proton": "ProtonDeDx"}
OUT = os.path.join(PDHD, "stm", "pdhd_ref_dqdx.json")


def read(path):
    f = uproot.open(path)
    out = {}
    for part, key in PARTS.items():
        g = f[part]
        x = g.values(axis="x"); y = g.values(axis="y")
        if len(x) == 61 and x[0] < 0:   # legacy synthetic point
            x, y = x[1:], y[1:]
        assert len(x) == 60 and abs(x[0] - 0.5) < 1e-9 and abs(x[1] - x[0] - 1.0) < 1e-9, (part, x[:3])
        out[key] = [float(v) for v in y]
    return out


def compiled_tables():
    tmp = "/home/xqian/tmp/chk_pds_ref.jsonnet"
    with open(tmp, "w") as fh:
        fh.write('local p = (import "%s")();\n' % JSONNET)
        fh.write("{ %s }\n" % ", ".join('%s: p.%s_dEdx_function.data.values' % (k, part) for part, k in PARTS.items()))
    return json.loads(subprocess.check_output(["wcsonnet", tmp]))


def main():
    t045 = read(ROOT045)
    cfg = compiled_tables()
    for key, vals in t045.items():
        rel = np.max(np.abs(np.array(cfg[key]) / np.array(vals) - 1.0))
        assert rel < 1e-5, (key, rel)      # emit_jsonnet_dedx.py prints 6 sig figs
    print("gate: 0.4959 kV/cm ROOT tables == compiled pdhd/particle_dataset.jsonnet (max rel < %.0e)" % 1e-5)
    mip045 = t045["MuonDeDx"][-1] * (56000.0 / 54657.7)
    out = {"_meta": {
        "what": "PDHD stopping-particle dQ/dx (e/cm) vs residual range (cm), Modified-Box tables.",
        "generator": "pdhd/docs/scripts/d42_make_ref_dqdx.py (fork of pdvd/docs/nf_sp_img_clus/scripts/d42_make_ref_dqdx_045.py)",
        "writeup": "pdhd/docs/stm-tagger-chain.md",
        "dedx_source": os.path.join(EL, "stopping.root"),
        "grid": "60 bins, centres 0.5 .. 59.5 cm, 10-point average of the pointwise dQ/dx inside each bin (convert_field.C)",
        "E_field_kVcm": 0.4959,
        "E_field_origin": "implied by the CALIBRATED PDHD drift velocity 1.576 mm/us at T = 87.68 K through the BNL "
                          "lar.bnl.gov/properties mobility parameterisation (pdhd/stm/pdhd_transport.py). The dunecore "
                          "nominal field is 0.4867 kV/cm; the difference moves the plateau by 0.34 %.",
        "W_ion_MeV": 2.36e-05,
        "Box_keys": {"model": "modified box: R = ln(A + xi)/xi, xi = (B/rho E) dEdx",
                     "A": 0.93, "B": 0.212, "rho": 1.38, "C": 0.85,
                     "note": "the *DeDx keys are the tables the PDHD PR config uses (pgrapher/experiment/pdhd/particle_dataset.jsonnet, "
                             "generated by convert_field.C at 0.4959 kV/cm). MIP_DQDX and anything reporting on a TaggerCheckSTM "
                             "decision must read THESE keys."},
        "mip_dqdx": {"pdhd": 56000, "rule": "SBND rule 56000 = plateau(rr 59.5) 54657.7 x 1.02456; PDHD plateau %.1f x 1.02456 = %.0f -> 56000"
                     % (t045["MuonDeDx"][-1], mip045), "mip_dqdx_median": 48000},
        "electron": "above 15 cm the curve is a clamp (ele1.dat ends at 15.3 cm), not physics; the 0.5 cm bin is held at the 1.5 cm value.",
    }}
    for key, vals in t045.items():
        out[key] = {"start": 0.5, "step": 1.0, "values": vals}
    with open(OUT, "w") as fh:
        json.dump(out, fh, indent=1)
    print("wrote", OUT)
    for key in ("MuonDeDx", "ProtonDeDx"):
        a = np.array(t045[key])
        print("  %-10s rr0.5 %.0f   rr59.5 %.0f" % (key, a[0], a[-1]))


if __name__ == "__main__":
    sys.exit(main())
