#!/usr/bin/env python3
"""Retirement round 2026-08-11 -- the pr/38-65 campaign sweep, 103 G -> ~23-24 G.

Fork of plan_20260805cs.py (the clean-slate round).  Same shape: with imaging
already regenerated by the doc-71 campaign and current production now toolkit
b38127a0 (pr/62 + pr/64 + pr/65 all flipped ON, 2026-08-11), the pre-08-11 arm
population is a record layer, not an input set -- so KEEP is again five
explicit-ish names, not a dependency-graph inference. This round's KEEP set is
larger (18, not 5) because run_valfast.sh now pins the img/cb0805 hub pairs
that the clean-slate round's campaign had not yet produced.

Two defects fixed vs the inherited (retire_20260805.sh / retire_20260805cs.sh)
scripts, found during exploration for this round -- see docs/work-tags.md
"RETIREMENT ROUND 2026-08-11":
  1. The survivor census in both prior drivers (`ls -d work* | wc -l`) counts
     the 118 orphan `work-*.driver.log` FILES alongside directories and can
     never match the expected count. This round's driver uses `-type d`.
  2. retire_20260805cs.sh:85 `tier{A}_...txt` is a single-element brace that
     bash leaves literal, silently degrading the Bokeh interlock to a no-op.
     Not inherited; the fork below iterates the TIERS argument properly.

NEW ASSERT 6: overclustering_labels/ (899 labels / 233 files, untracked +
gitignored) has a verified byte-identical archive copy AND is committed to git
-- both discharged by this round's Phase 2, done before this script runs.

NEW: EXTRA handles two removal classes invisible to the `work*` glob that every
prior plan_*.py missed -- VOID-pr32-round1/ (6 dead pr/32 arms bundled under a
non-`work`-prefixed name) and the 118 `work-*.driver.log` orphan files. Both
get their own tier-A-shaped treatment: VOID-pr32-round1 is archived as one unit
(group 'legacy-void') then removed; the driver logs are tarred as one bundle
(scripts/retire/state-20260811/driver-logs.tar.gz) then removed -- handled by
retire_20260811.sh, not by the `work*` per-dir loop.

scan-d59k/bee/ (694 MB, 9 Bee zips) is a THIRD special case, deliberately NOT
archived: all 9 zips already have a saved `.url` (checked -- unlike the 08-03
round, which found only 12/44), so the sets are already live on the BNL twister
server and dropping the local zip is not a one-way loss of a display, just of a
redundant copy. Its record layer (.url/.index.txt/.stmid-map.txt/.build.log)
stays in place, and the hand-scan .tsv/.txt tables were additionally copied to
archive/records/labels/scan-d59k/ in Phase 2. Handled by retire_20260811.sh.

Writes scripts/retire/tierA_20260811.txt and state-20260811/plan.json.
Read-only w.r.t. work-* (and VOID-pr32-round1, and the driver-log files).
"""
import os, re, json, subprocess, collections, sys, filecmp

ROOT = "/nfs/data/1/xqian/toolkit-dev/wcp-porting-img/sbnd/sbnd_xin"
SCR = os.path.join(ROOT, "scripts", "retire")
STATE = os.environ.get("RETIRE_STATE", os.path.join(SCR, "state-20260811"))
os.makedirs(STATE, exist_ok=True)
os.chdir(ROOT)

if os.path.exists(os.path.join(STATE, "removed.tsv")) and not os.environ.get("RETIRE_REPLAN"):
    sys.stderr.write(
        f"REFUSING: {STATE}/removed.tsv exists -- this round has already run (M13).\n"
        f"Fork with a new date/state for a new round; RETIRE_REPLAN=1 to override.\n")
    sys.exit(3)

dirs = sorted(d for d in os.listdir('.')
              if d.startswith('work') and os.path.isdir(d) and not os.path.islink(d))

# EXTRA universe member: VOID-pr32-round1/ (6 dead pr/32 arms bundled under a
# non-`work`-prefixed name) is invisible to every prior round's `work*` glob.
# It is a real dir (not a symlink), holds 0 symlinks and 0 git-tracked files
# (checked) -- flows through the same archive-then-delete machinery as any
# other tier-A arm once added to the universe explicitly.
if os.path.isdir('VOID-pr32-round1') and not os.path.islink('VOID-pr32-round1'):
    dirs.append('VOID-pr32-round1')
    dirs.sort()

# ---------------------------------------------------------------- KEEP
KEEP_WHY = {
    # imaging hubs -- runner-pinned (valfast/run_valfast.sh), 1090 inbound symlinks
    'work-img-mcp1k':        'imaging hub, 1000 inbound symlinks, run_valfast.sh pin',
    'work-img-nuecc48':      'imaging hub, 48 inbound symlinks, run_valfast.sh pin',
    'work-img-ncpi0':        'imaging hub, 19 inbound symlinks, run_valfast.sh pin',
    'work-img-r1qlmc':       'imaging hub, 10 inbound symlinks, run_valfast.sh pin',
    'work-img-r2mc':         'imaging hub, 13 inbound symlinks, run_valfast.sh pin',
    # Q/L hubs -- runner-pinned, thinned in Phase 4 (pr_evt*/nusel_evt*/calib dropped)
    'work-mcp1k-cb0805':     'Q/L hub, run_valfast.sh + run_full1k_nusel.sh pin',
    'work-nuecc48-cb0805':   'Q/L hub, run_valfast.sh + geom_ab_batch.sh pin',
    'work-ncpi0-cb0805':     'Q/L hub, run_valfast.sh pin',
    'work-r1qlmc-cb0805':    'Q/L hub, run_valfast.sh pin',
    'work-r2mc-cb0805':      'Q/L hub, run_valfast.sh pin',
    # current-production reference arms (toolkit b38127a0) -- 2026-08-11 Bee sources
    'work-pr64r4-on48':      'current-production PR reference, nueCC48 Bee source',
    'work-pr64r4-on19':      'current-production PR reference, NCpi0 Bee source',
    'work-pr64r4-on1k':      'current-production PR reference, mcp1k-50 Bee source (full 1k kept)',
    # oc56 truth-table dumps (scripts/analysis/pr57/oc56_truth.py DEFAULT_ARMS)
    'work-pr64r4-scan48':    'oc56 scan-dump arm, oc56_truth.py DEFAULT_ARMS',
    'work-pr64r4-scan19':    'oc56 scan-dump arm, oc56_truth.py DEFAULT_ARMS',
    # git-tracked / M13
    'work-stmcamp-d66new':   'git-tracked nusel_labels/ hand-scan state (M13)',
    'work-nuecc48-prsmoke2': '3 git-tracked runner scripts',
    'work-tfix388-r9':       'doc pr/28 sec.15.9 -- NOT reproducible from any surviving input',
}
KEEP = set(KEEP_WHY)

# ---- what the owner released from PROTECTED.txt (superseded this round) -----
def read_protected(path):
    out = set()
    if not os.path.exists(path):
        return out
    for line in open(path):
        line = line.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        out.update(line.split("\t")[0].split())
    return out


PROT_LISTED = read_protected(os.path.join(SCR, "PROTECTED.txt"))
# work-pr33-{base,off}48 are PROTECTED.txt survivors of the cs round, retired
# this round (owner decision: superseded by the cb0805 campaign and everything
# since). Everything else in PROT_LISTED is already gone from disk.
RELEASED = sorted(PROT_LISTED - KEEP)


def tier(d):
    return 'KEEP' if d in KEEP else 'A'


def group(d):
    for pat, g in ((r'^VOID-pr32-round1$', 'legacy-void'),
                   (r'^work-img-', 'imaging-hubs'),
                   (r'^work-.*-cb0805$', 'ql-hubs'),
                   (r'^work-pr64r4-', 'pr64r4-reference'),
                   (r'^work-pr6[0-5]', 'pr60-65-era'),
                   (r'^work-pr5[0-9]', 'pr50-59-era'),
                   (r'^work-pr4[0-9]', 'pr40-49-era'),
                   (r'^work-pr3[0-9]', 'pr30-39-era'),
                   (r'^work-vf', 'valfast-transient'),
                   (r'^work-nuecc48', 'nuecc48-arms'),
                   (r'^work-ncpi0', 'ncpi0-arms'),
                   (r'^work-mcp1k', 'mcp1k-arms'),
                   (r'^work-(r1ql|r2mc|r2patrec)', 'mc-sample-arms')):
        if re.match(pat, d):
            return g
    return 'other'


bytier = collections.defaultdict(list)
for d in dirs:
    bytier[tier(d)].append(d)

K, TA = bytier['KEEP'], bytier['A']
R = sorted(TA)
ARCHIVE = sorted(TA)
assert len(dirs) == len(R) + len(K), "classes do not partition work*"
missing_keep = sorted(KEEP - set(dirs))

# ---------------------------------------------------------------- footprint
# HEAVY extends the 08-05 set: tracking-pr.root and oc56scan-evt*.jsonl are
# reclassified as drop this round (see docstring).
HEAVY = (re.compile(r'^pctree.*\.tar\.gz$'), re.compile(r'^mabc.*\.zip$'),
         re.compile(r'^calib(-pr)?-evt.*\.json(\.gz)?$'), re.compile(r'.*\.npz$'),
         re.compile(r'^clusters-apa.*\.tar\.gz$'),
         re.compile(r'^opflash_apa.*\.tar\.gz$'),
         re.compile(r'^tracking-pr\.root$'),
         re.compile(r'^oc56scan-evt.*\.jsonl$'))


def is_heavy(f):
    return any(p.match(f) for p in HEAVY)


SPDATA = re.compile(r'^(sp-frames.*\.tar\.bz2|sbnd-sp-frames.*\.tar\.bz2|frames-dnn\.tar\.bz2)$')
RECORD_DIR = re.compile(r'^(nusel_labels|ql_labels|decisions.*)$')

per = {}
label_hits = []
for d in R:
    tot = keep = nk = nh = 0
    for cur, sub, files in os.walk(d):
        sub[:] = [s for s in sub if not os.path.islink(os.path.join(cur, s))]
        for s in sub:
            if RECORD_DIR.match(s):
                label_hits.append(os.path.join(cur, s))
        for f in files:
            p = os.path.join(cur, f)
            if os.path.islink(p):
                continue
            try:
                sz = os.path.getsize(p)
            except OSError:
                continue
            tot += sz
            if is_heavy(f):
                nh += 1
            else:
                keep += sz
                nk += 1
    per[d] = dict(tot=tot, keep=keep, nk=nk, nh=nh)

# ---------------------------------------------------------------- report
print("=== RETIREMENT ROUND 2026-08-11 ===")
print(f"universe {len(dirs)} work* dirs -> KEEP {len(K)}, remove {len(R)}")
if missing_keep:
    print(f"!! KEEP names not on disk: {missing_keep}")
print("\n[KEEP]")
for d in sorted(K):
    print(f"    {d:26s} {per.get(d,{}).get('tot',0)/2**20:8.0f} MB  {KEEP_WHY[d]}")
print(f"\n[REMOVE] {len(R)} dirs, {sum(per[d]['tot'] for d in R)/2**30:.2f} GiB")
for d in sorted(R, key=lambda x: -per[x]['tot'])[:30]:
    print(f"    {d:26s} {per[d]['tot']/2**20:8.0f} MB  [{group(d)}]")
if len(R) > 30:
    print(f"    ... and {len(R)-30} more (full list: tierA_20260811.txt)")

print(f"\n[RELEASED from PROTECTED.txt, superseded 2026-08-11] {len(RELEASED)}")
print("    " + " ".join(RELEASED))

print("\n=== ARCHIVE FOOTPRINT ===")
stat = collections.defaultdict(lambda: [0, 0, 0])
for d in ARCHIVE:
    s = stat[group(d)]
    s[0] += per[d]['tot']; s[1] += per[d]['keep']; s[2] += per[d]['nk']
for g in sorted(stat):
    t, k, nk = stat[g]
    print(f"{g:20s} total {t/2**30:6.2f} GiB  archive {k/2**20:8.1f} MiB ({nk} files)  "
          f"reclaim {(t-k)/2**30:6.2f} GiB")
T = sum(per[d]['tot'] for d in R)
Kb = sum(stat[g][1] for g in stat)
print(f"{'TOTAL':20s} total {T/2**30:6.2f} GiB  archive {Kb/2**20:8.1f} MiB  "
      f"reclaim {(T-Kb)/2**30:6.2f} GiB")

# ---------------------------------------------------------------- asserts
fail = 0

print("\n=== ASSERT 1: no real SP frame is lost -- source dirs survive locally ===")
SP_SOURCES = {
    'mcp1k (1000 data)':  'input_files_reco1/staged-mcp2025c-1000evt',
    'nuecc48 (48 data)':  'input_files_reco1/extracted-2025fall-48evt-fsprod',
    'ncpi0 (19 data)':    'input_files_reco1/extracted-ncpi0',
    'r1qlmc (10 sim)':    'input_files_reco1/extracted-r1ql-f1',
    'r2mc (13 sim)':      'input_files_reco1/extracted-r2patrec-f1',
}
for label, src in sorted(SP_SOURCES.items()):
    ok = os.path.isdir(src) and not os.path.islink(src) and bool(os.listdir(src))
    n = len(os.listdir(src)) if os.path.isdir(src) else 0
    print(f"      {'OK ' if ok else '!! '} {label:20s} {src}  ({n} entries)")
    if not ok:
        fail += 1
print("    work-img-mcp1k's sp-frames*.tar.bz2 (1.23 GiB) is what actually drops in Phase 4;")
print("    every other sample's SP layer is untouched by this round.")

print("\n=== ASSERT 2: every hand-scan / label record has a verified archive copy (M13) ===")
LABROOT = os.path.join(ROOT, "archive", "records", "labels")


def tree_identical(a, b):
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.funny_files:
        return False
    _, mismatch, errors = filecmp.cmpfiles(a, b, cmp.common_files, shallow=False)
    if mismatch or errors:
        return False
    return all(tree_identical(os.path.join(a, d), os.path.join(b, d))
               for d in cmp.common_dirs)


if not label_hits:
    print("0 label dirs in the removal set -- PASS (strict form)")
else:
    for p in sorted(label_hits):
        rel = os.path.relpath(p, ROOT)
        dst = os.path.join(LABROOT, rel)
        nsrc = sum(len(f) for _, _, f in os.walk(p))
        if not os.path.isdir(dst):
            print(f"  !! NO ARCHIVE COPY: {rel}")
            fail += 1
        elif not tree_identical(p, dst):
            print(f"  !! ARCHIVE COPY DIFFERS: {rel}")
            fail += 1
        else:
            ntag = len(os.listdir(p))
            print(f"  OK  {rel:38s} {ntag:2d} tags, {nsrc:3d} files -> archive copy verified")

print("\n=== ASSERT 3: no git-tracked file inside the removal set ===")
tracked = subprocess.run(['git', '-C', '/nfs/data/1/xqian/toolkit-dev/wcp-porting-img',
                           'ls-files', '-z', '--'] + ['sbnd/sbnd_xin/' + d for d in R],
                          capture_output=True, text=True).stdout.split('\0')
tracked = [t for t in tracked if t]
if not tracked:
    print("0 -- PASS")
else:
    fail += 1
    for t in tracked[:50]:
        print(f"  !! {t}")

print("\n=== ASSERT 4: dangling-link dry run ===")
Rset = set(R)
bad = collections.Counter()
nlinks = 0
top = [e for e in sorted(os.listdir('.')) if e not in Rset and not e.startswith('.')]
for root in top:
    if os.path.islink(root):
        m = re.search(r'sbnd_xin/(work[^/]*)', os.readlink(root))
        if m and m.group(1) in Rset:
            bad[(root, m.group(1))] += 1
        continue
    if not os.path.isdir(root):
        continue
    for cur, sub, files in os.walk(root, followlinks=False):
        for name in sub + files:
            p = os.path.join(cur, name)
            if os.path.islink(p):
                nlinks += 1
                m = re.search(r'sbnd_xin/(work[^/]*)', os.readlink(p))
                if m and m.group(1) in Rset:
                    bad[(root, m.group(1))] += 1
print(f"({nlinks} symlinks outside removal set)")
if not bad:
    print("0 -- PASS")
else:
    fail += 1
    for (s, t), c in bad.most_common():
        print(f"  !! {c:6d}  {s} -> {t}")

print("\n=== ASSERT 5: every KEEP name exists and is non-empty ===")
bad_keep = [d for d in KEEP if not (os.path.isdir(d) and os.listdir(d))]
print("0 -- PASS" if not bad_keep else f"  !! {bad_keep}")
if bad_keep:
    fail += 1

print("\n=== ASSERT 6 (NEW): overclustering_labels archived + git-tracked ===")
occ_src = os.path.join(ROOT, "overclustering_labels")
occ_dst = os.path.join(LABROOT, "overclustering_labels")
if not os.path.isdir(occ_dst):
    print("  !! NO ARCHIVE COPY at archive/records/labels/overclustering_labels")
    fail += 1
elif not tree_identical(occ_src, occ_dst):
    print("  !! ARCHIVE COPY DIFFERS from live overclustering_labels/")
    fail += 1
else:
    gitcount = subprocess.run(
        ['git', '-C', '/nfs/data/1/xqian/toolkit-dev/wcp-porting-img', 'ls-files',
         'sbnd/sbnd_xin/overclustering_labels'],
        capture_output=True, text=True).stdout.strip().splitlines()
    if len(gitcount) < 200:
        print(f"  !! only {len(gitcount)} files git-tracked under overclustering_labels (expect >=230)")
        fail += 1
    else:
        print(f"  OK  archive copy verified identical, {len(gitcount)} files committed to git")

# ---------------------------------------------------------------- emit
with open(os.path.join(SCR, "tierA_20260811.txt"), "w") as fh:
    fh.write("\n".join(sorted(TA)) + "\n")
json.dump({'A': sorted(TA), 'D': [], 'R': R, 'ARCHIVE': ARCHIVE,
           'KEEP': sorted(K), 'KEEP_WHY': KEEP_WHY, 'HUB': [], 'POSTBUILD': [],
           'PROTECTED': sorted(KEEP & PROT_LISTED), 'RELEASED': RELEASED,
           'per': per, 'cites': {},
           'group': {d: group(d) for d in dirs}},
          open(os.path.join(STATE, "plan.json"), "w"), indent=1)
print(f"\nremoval set: {len(R)} dirs -> scripts/retire/tierA_20260811.txt")
print(f"survivors: {len(K)}")
print(f"state: {STATE}/plan.json")
print("\nOVERALL: " + ("PASS -- all asserts clean" if not fail
                       else f"FAIL -- {fail} assert(s) tripped, do not proceed"))
sys.exit(0 if not fail else 1)
