#!/usr/bin/env python3
"""
Compare PDVD per-channel electronics-noise RMS: data vs. noise-only simulation.

Reads noise_rms_data.npz and noise_rms_sim.npz (produced by noise_rms.py),
overlays data and simulation RMS-vs-channel for every anode / plane, builds a
summary figure, and writes the comparison report noise_rms_comparison.md.

Run noise_rms.py --source data and --source sim first.

Usage:  ./noise_rms_compare.py
"""
import os

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(SCRIPTDIR, 'noise_rms')

PLANES = ['U', 'V', 'W']
NANODE = 8

# Digitizer LSB (V/count) per drift volume, from cfg/.../protodunevd:
#   resolution = 14 bits -> 2**14 = 16384 counts
#   bottom (anodes 0-3): fullscale [0.2, 1.6] V  -> span 1.4 V
#   top    (anodes 4-7): fullscale [0.0, 2.0] V  -> span 2.0 V
LSB_UV = {'bottom': 1.4 / 16384 * 1e6, 'top': 2.0 / 16384 * 1e6}   # microvolt/count


def region(n):
    return 'bottom' if n < 4 else 'top'


def load(src):
    return dict(np.load(os.path.join(OUTDIR, 'noise_rms_%s.npz' % src)))


def plot_anode(n, data, sim):
    loc = region(n)
    fig, axes = plt.subplots(3, 1, figsize=(11, 9))
    fig.suptitle('PDVD noise RMS: data vs. simulation  --  anode %d (%s drift)'
                 % (n, loc), fontsize=12)
    for ax, pl in zip(axes, PLANES):
        d = data['anode%d_%s_rms' % (n, pl)]
        s = sim['anode%d_%s_rms' % (n, pl)]
        ax.plot(np.arange(len(d)), d, lw=0.8, color='C0',
                label='data    median = %.2f ADC' % np.median(d))
        ax.plot(np.arange(len(s)), s, lw=0.8, color='C1',
                label='sim     median = %.2f ADC' % np.median(s))
        ax.set_ylabel('noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xlim(0, max(len(d), len(s)) - 1)
        ax.set_ylim(0, max(np.percentile(d, 99), np.percentile(s, 99)) * 1.35)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, loc='upper right')
    axes[-1].set_xlabel('channel index within plane')
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_anode%d.png' % n)
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def plot_summary(data, sim):
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.suptitle('PDVD noise RMS: data vs. simulation  --  per-anode median '
                 '(anodes 0-3 bottom, 4-7 top)', fontsize=12)
    x = np.arange(NANODE)
    for ax, pl in zip(axes, PLANES):
        dmed = [np.median(data['anode%d_%s_rms' % (n, pl)]) for n in x]
        smed = [np.median(sim['anode%d_%s_rms' % (n, pl)]) for n in x]
        ax.plot(x, dmed, 'o-', color='C0', label='data')
        ax.plot(x, smed, 's--', color='C1', label='sim')
        ax.axvline(3.5, color='0.5', ls=':', lw=1)
        ax.text(1.5, ax.get_ylim()[1], 'bottom', ha='center', va='top', fontsize=9)
        ax.text(5.5, ax.get_ylim()[1], 'top', ha='center', va='top', fontsize=9)
        ax.set_xlabel('anode')
        ax.set_ylabel('median noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xticks(x)
        ax.set_ylim(0, None)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9)
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_summary.png')
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def region_median(arrs, src, anodes, pl):
    """Median RMS over all channels of the given anodes/plane."""
    vals = np.concatenate([arrs['anode%d_%s_rms' % (n, pl)] for n in anodes])
    return float(np.median(vals))


def write_md(data, sim):
    bot, top = [0, 1, 2, 3], [4, 5, 6, 7]

    # region x plane summary
    rows = []
    for name, anodes in [('bottom', bot), ('top', top)]:
        for pl in PLANES:
            d = region_median(data, 'data', anodes, pl)
            s = region_median(sim, 'sim', anodes, pl)
            lsb = LSB_UV[name]
            rows.append((name, pl, d, s, s / d,
                         d * lsb / 1e3, s * lsb / 1e3))   # mV equivalents

    lines = []
    A = lines.append
    A('# PDVD electronics noise: data vs. simulation')
    A('')
    A('Per-channel electronics-noise RMS for ProtoDUNE Vertical Drift, comparing '
      'real data against the noise-only simulation. Generated by '
      '`noise_rms_compare.py`.')
    A('')
    A('## Question')
    A('')
    A('Is the PDVD electronics-noise simulation consistent with data?')
    A('')
    A('## Inputs and method')
    A('')
    A('- **Data**: PDVD `run039324`, event 0 — raw pre-NF ADC frames '
      '(`protodune-orig-frames-anode{0-7}.tar.bz2`), all 8 anodes.')
    A('- **Simulation**: noise-only run of the production noise chain '
      '(`pdvd_sim/wct-sim-noise-only.jsonnet`): `EmpiricalNoiseModel` + '
      '`AddNoise` + `Digitizer`, configuration taken verbatim from '
      '`cfg/pgrapher/experiment/protodunevd/sim.jsonnet`.')
    A('- **Noise RMS**: per channel, replicating WireCell sigproc '
      '`Derivations::CalcRMS` (`sigproc/src/Derivations.cxx`) — a one-pass '
      '4.5σ clip that excludes signal samples, then the population RMS of the '
      'rest. Measured on the raw ADC waveform, before noise filtering.')
    A('- Anodes 0-3 are the **bottom** drift volume, 4-7 the **top**.')
    A('')
    A('## Result — the simulation is NOT consistent with data')
    A('')
    A('Median noise RMS over all channels of each drift volume / plane:')
    A('')
    A('| region | plane | data [ADC] | sim [ADC] | sim/data | data [mV] | sim [mV] |')
    A('|--------|-------|-----------:|----------:|---------:|----------:|---------:|')
    for name, pl, d, s, r, dmv, smv in rows:
        A('| %s | %s | %.2f | %.2f | %.2f | %.3f | %.3f |'
          % (name, pl, d, s, r, dmv, smv))
    A('')
    A('Two clear failures:')
    A('')
    A('1. **The top/bottom ordering is inverted.** In data the top drift volume '
      'is markedly noisier than the bottom (top ≈ 13 ADC vs bottom ≈ 7-8 ADC). '
      'In simulation it is the opposite — the bottom is noisier than the top '
      '(bottom ≈ 11-13 ADC vs top ≈ 8.5-9 ADC).')
    A('2. **Both regions are mis-normalised.** The simulation **overestimates '
      'bottom** noise by roughly 1.6-1.8× and **underestimates top** noise by '
      'roughly 0.65×.')
    A('')
    A('### Voltage-equivalent view')
    A('')
    A('ADC-count RMS folds in the digitizer LSB, which differs by drift volume '
      '(bottom span 1.4 V → %.1f µV/count; top span 2.0 V → %.1f µV/count, at '
      '14-bit resolution). Converting to voltage (mV columns above) shows the '
      'physical picture: the **model produces a nearly uniform ≈1.1 mV** RMS in '
      'both volumes, whereas the **real detector has a quiet bottom (≈0.6 mV) '
      'and a loud top (≈1.6 mV)**. The bottom noise spectra file over-predicts; '
      'the top noise spectra file under-predicts.'
      % (LSB_UV['bottom'], LSB_UV['top']))
    A('')
    A('### Contributing factor: no coherent noise in the simulation')
    A('')
    A('The PDVD sim adds noise with `AddNoise` (`IncoherentAddNoise`) only — '
      'there is no `CoherentAddNoise` in `sim.jsonnet`. Real data noise is '
      'incoherent + coherent. Missing coherent noise can only make the sim '
      '*lower* than data, so it contributes to the top under-prediction but '
      'cannot explain the bottom *over*-prediction — that is a mis-normalised '
      'incoherent spectra file (`pdvd-bottom-noise-spectra-v1.json.bz2`).')
    A('')
    A('## Per-anode comparison')
    A('')
    for n in range(NANODE):
        A('### anode %d (%s)' % (n, region(n)))
        A('')
        A('![anode %d](noise_rms/noise_rms_compare_anode%d.png)' % (n, n))
        A('')
    A('## Summary across anodes')
    A('')
    A('![summary](noise_rms/noise_rms_compare_summary.png)')
    A('')
    A('Per-source overviews (all 8 anodes overlaid):')
    A('')
    A('![data](noise_rms/noise_rms_data_summary.png)')
    A('')
    A('![sim](noise_rms/noise_rms_sim_summary.png)')
    A('')
    A('## Full per-anode / per-plane table')
    A('')
    A('| anode | region | plane | data [ADC] | sim [ADC] | sim/data |')
    A('|------:|--------|-------|-----------:|----------:|---------:|')
    for n in range(NANODE):
        for pl in PLANES:
            d = float(np.median(data['anode%d_%s_rms' % (n, pl)]))
            s = float(np.median(sim['anode%d_%s_rms' % (n, pl)]))
            A('| %d | %s | %s | %.2f | %.2f | %.2f |'
              % (n, region(n), pl, d, s, s / d))
    A('')
    A('## Caveats')
    A('')
    A('- **Per-region comparison is valid**: data and sim use the same ADC '
      'scale within a drift volume, so data-vs-sim within bottom (or within '
      'top) is apples-to-apples. The top-vs-bottom comparison instead folds in '
      'the different LSB — hence the mV columns.')
    A('- **Residual signal in data**: event 0 is a real triggered event. The '
      'one-pass `CalcRMS` clip leaves a small (~5-10%) residual-signal bias on '
      'the busier (top) planes; a 3-pass iterative clip cross-check gave '
      'data top U/V/W ≈ 12.8/12.9/13.0 ADC vs the 14.2/13.2/13.8 reported '
      'here. This does not change any conclusion.')
    A('- **Tick period**: data is 512 ns/tick (native, pre-resampler), sim is '
      '500 ns/tick. This is a sub-1% effect on ADC-count RMS and is not '
      'corrected.')
    A('- The simulation was run with `nticks = 10000`; data frames have '
      '6250 (bottom) / 6400 (top) ticks — ample statistics for a per-channel '
      'RMS in both cases.')
    A('')
    A('## Conclusion')
    A('')
    A('The PDVD electronics-noise simulation does **not** reproduce the data. '
      'The two input noise-spectra files need re-tuning: '
      '`pdvd-bottom-noise-spectra-v1.json.bz2` over-predicts the bottom drift '
      'volume and `pdvd-top-noise-spectra-v2.json.bz2` under-predicts the top, '
      'so the characteristic quiet-bottom / loud-top pattern seen in data is '
      'absent — in fact inverted — in simulation. Adding a coherent-noise '
      'component would further widen the top gap. See '
      '`pdvd_noise_simulation.md` for how the noise model is built.')
    A('')

    out = os.path.join(SCRIPTDIR, 'noise_rms_comparison.md')
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines))
    print('  wrote %s' % out)


def main():
    data, sim = load('data'), load('sim')
    print('=== data vs sim comparison ===')
    for n in range(NANODE):
        plot_anode(n, data, sim)
    plot_summary(data, sim)
    write_md(data, sim)
    print('done.')


if __name__ == '__main__':
    main()
