retile_sampler_strategy='charge_stepped'
steiner_blank_plane_mode='prefer3'
steiner_base_weight_blank_alpha=0.5
steiner_base_weight_scope='tree+path'
steiner_terminal_min_separation=0.7
retile_sampler_charge_threshold=6000
dl_vtx_min_accept_score=4.0
