#!/usr/bin/env python3
"""doc pdvd/42: the PDVD stopping-particle dQ/dx-vs-residual-range reference json
at E = 0.45 kV/cm -- the tables the PRODUCTION config has carried since
2026-09-03 (cfg/pgrapher/experiment/protodunevd/particle_dataset.jsonnet, doc
pdvd/29).  Fork by duplication of pdvd/stm/make_pdvd_ref_dqdx.py, which wrote
the 0.44 kV/cm set that doc 25 sec 13.6 was graded against; that file and its
output pdvd/stm/pdvd_ref_dqdx.json are left untouched as the doc-25 record.

Self-gate: the 0.45 tables read from the ROOT file must equal the compiled
jsonnet before anything is written.  The 0.50 kV/cm comparison set is carried
under the *_E050 keys exactly as before.

Repro:
  cd /nfs/data/1/xqian/toolkit-dev/wcp-porting-img/pdvd
  python3 docs/nf_sp_img_clus/scripts/d42_make_ref_dqdx_045.py   # writes stm/pdvd_ref_dqdx_045.json
"""
import json
import os
import subprocess
import sys

import numpy as np
import uproot

HERE = os.path.dirname(os.path.realpath(__file__))
PDVD = os.path.normpath(os.path.join(HERE, "..", "..", ".."))        # wcp-porting-img/pdvd
TOP = os.path.normpath(os.path.join(PDVD, "..", ".."))              # toolkit-dev
EL = os.path.join(TOP, "energy_loss", "pion_travel")
ROOT045 = os.path.join(EL, "stopping_ave_dQ_dx_pdvd045.root")
ROOT050 = os.path.join(EL, "stopping_ave_dQ_dx_pdvd050.root")
JSONNET = "pgrapher/experiment/protodunevd/particle_dataset.jsonnet"
PARTS = {"muon": "MuonDeDx", "electron": "ElectronDeDx", "pion": "PionDeDx",
         "kaon": "KaonDeDx", "proton": "ProtonDeDx"}
OUT = os.path.join(PDVD, "stm", "pdvd_ref_dqdx_045.json")


def read(path):
    f = uproot.open(path)
    out = {}
    for part, key in PARTS.items():
        g = f[part]
        x = g.values(axis="x"); y = g.values(axis="y")
        if len(x) == 61 and x[0] < 0:   # legacy synthetic point
            x, y = x[1:], y[1:]
        assert len(x) == 60 and abs(x[0] - 0.5) < 1e-9 and abs(x[1] - x[0] - 1.0) < 1e-9, (part, x[:3])
        out[key] = [float(v) for v in y]
    return out


def compiled_tables():
    tmp = "/home/xqian/tmp/chk_pds_ref.jsonnet"
    with open(tmp, "w") as fh:
        fh.write('local p = (import "%s")();\n' % JSONNET)
        fh.write("{ %s }\n" % ", ".join('%s: p.%s_dEdx_function.data.values' % (k, part) for part, k in PARTS.items()))
    return json.loads(subprocess.check_output(["wcsonnet", tmp]))


def main():
    t045 = read(ROOT045)
    t050 = read(ROOT050)
    cfg = compiled_tables()
    for key, vals in t045.items():
        rel = np.max(np.abs(np.array(cfg[key]) / np.array(vals) - 1.0))
        assert rel < 1e-5, (key, rel)      # emit_jsonnet_dedx.py prints 6 sig figs
    print("gate: 0.45 kV/cm ROOT tables == compiled protodunevd/particle_dataset.jsonnet (max rel < %.0e)" % 1e-5)
    mip045 = t045["MuonDeDx"][-1] * (56000.0 / 54657.7)
    out = {"_meta": {
        "what": "PDVD stopping-particle dQ/dx (e/cm) vs residual range (cm), Modified-Box tables.",
        "generator": "pdvd/docs/nf_sp_img_clus/scripts/d42_make_ref_dqdx_045.py (fork of pdvd/stm/make_pdvd_ref_dqdx.py)",
        "writeup": "pdvd/docs/nf_sp_img_clus/42_stm-fit-2d-charge-and-dqdx-validation.md",
        "dedx_source": os.path.join(EL, "stopping.root"),
        "grid": "60 bins, centres 0.5 .. 59.5 cm, 10-point average of the pointwise dQ/dx inside each bin (convert_field.C)",
        "E_field_kVcm": 0.45,
        "E_field_origin": "implied by the data-calibrated drift velocity 1.48073 mm/us at T = 87.68 K through the BNL "
                          "lar.bnl.gov/properties mobility parameterisation (pdvd/stm/pdvd_transport.py); owner 2026-09-02: "
                          "trust the velocity, the dQ/dx-vs-rr data comparison confirms the field",
        "W_ion_MeV": 2.36e-05,
        "Box_keys": {"model": "modified box: R = ln(A + xi)/xi, xi = (B/rho E) dEdx",
                     "A": 0.93, "B": 0.212, "rho": 1.38, "C": 0.85,
                     "note": "the *DeDx keys are the tables the running PDVD config uses (protodunevd/particle_dataset.jsonnet, "
                             "generated by convert_field.C at 0.45 kV/cm (2026-09-03, doc pdvd/29)). MIP_DQDX and anything reporting on a TaggerCheckSTM "
                             "decision must read THESE keys."},
        "E050_keys": {"model": "same Modified Box at E = 0.50 kV/cm (stopping_ave_dQ_dx_pdvd050.root); comparison set for the "
                               "field confirmation on data, NOT what the config uses"},
        "mip_dqdx": {"pdvd": 55000, "rule": "SBND rule 56000 = plateau(rr 59.5) 54657.7 x 1.02456; PDVD plateau %.1f x 1.02456 = %.0f -> 55000"
                     % (t045["MuonDeDx"][-1], mip045), "mip_dqdx_median": 47000},
        "electron": "above 15 cm the curve is a clamp (ele1.dat ends at 15.3 cm), not physics; the 0.5 cm bin is held at the 1.5 cm value.",
    }}
    for key, vals in t045.items():
        out[key] = {"start": 0.5, "step": 1.0, "values": vals}
    for key, vals in t050.items():
        out[key + "_E050"] = {"start": 0.5, "step": 1.0, "values": vals}
    with open(OUT, "w") as fh:
        json.dump(out, fh, indent=1)
    print("wrote", OUT)
    for key in ("MuonDeDx", "ProtonDeDx"):
        a, b = np.array(t045[key]), np.array(t050[key])
        print("  %-10s rr0.5 %.0f vs %.0f (%.1f%%)  rr59.5 %.0f vs %.0f (%.1f%%)" % (
            key, a[0], b[0], 100 * (a[0] / b[0] - 1), a[-1], b[-1], 100 * (a[-1] / b[-1] - 1)))


if __name__ == "__main__":
    sys.exit(main())
