#!/usr/bin/env python3
"""
Compare PDHD per-channel electronics-noise RMS: data vs. noise-only simulation.

Reads noise_rms_data.npz and noise_rms_sim.npz (produced by noise_rms.py),
overlays data and simulation RMS-vs-channel for every APA / plane, builds a
summary figure, and writes the comparison report noise_rms_comparison.md.

Run noise_rms.py --source data and --source sim first.

Usage:  ./noise_rms_compare.py
"""
import os

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(SCRIPTDIR, 'noise_rms')

PLANES = ['U', 'V', 'W']
NANODE = 4

# Digitizer LSB (V/count), from cfg/pgrapher/experiment/pdhd/params.jsonnet:
#   resolution = 14 bits -> 2**14 = 16384 counts
#   fullscale [0.2, 1.6] V -> span 1.4 V   (uniform across all 4 APAs)
LSB_UV = 1.4 / 16384 * 1e6   # microvolt/count


def load(src):
    return dict(np.load(os.path.join(OUTDIR, 'noise_rms_%s.npz' % src)))


def plot_anode(n, data, sim):
    fig, axes = plt.subplots(3, 1, figsize=(11, 9))
    fig.suptitle('PDHD noise RMS: data vs. simulation  --  APA %d' % n,
                 fontsize=12)
    for ax, pl in zip(axes, PLANES):
        d = data['anode%d_%s_rms' % (n, pl)]
        s = sim['anode%d_%s_rms' % (n, pl)]
        ax.plot(np.arange(len(d)), d, lw=0.8, color='C0',
                label='data    median = %.2f ADC' % np.median(d))
        ax.plot(np.arange(len(s)), s, lw=0.8, color='C1',
                label='sim     median = %.2f ADC' % np.median(s))
        ax.set_ylabel('noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xlim(0, max(len(d), len(s)) - 1)
        ax.set_ylim(0, max(np.percentile(d, 99), np.percentile(s, 99)) * 1.35)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, loc='upper right')
    axes[-1].set_xlabel('channel index within plane')
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_anode%d.png' % n)
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def plot_summary(data, sim):
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.suptitle('PDHD noise RMS: data vs. simulation  --  per-APA median',
                 fontsize=12)
    x = np.arange(NANODE)
    for ax, pl in zip(axes, PLANES):
        dmed = [np.median(data['anode%d_%s_rms' % (n, pl)]) for n in x]
        smed = [np.median(sim['anode%d_%s_rms' % (n, pl)]) for n in x]
        ax.plot(x, dmed, 'o-', color='C0', label='data')
        ax.plot(x, smed, 's--', color='C1', label='sim')
        ax.set_xlabel('APA')
        ax.set_ylabel('median noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xticks(x)
        ax.set_ylim(0, None)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9)
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_summary.png')
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def med(arrs, n, pl):
    return float(np.median(arrs['anode%d_%s_rms' % (n, pl)]))


def write_md(data, sim):
    # per-APA / per-plane medians
    rows = [(n, pl, med(data, n, pl), med(sim, n, pl)) for n in range(NANODE)
            for pl in PLANES]
    ratios = [s / d for _, _, d, s in rows]

    lines = []
    A = lines.append
    A('# PDHD electronics noise: data vs. simulation')
    A('')
    A('Per-channel electronics-noise RMS for ProtoDUNE Horizontal Drift, '
      'comparing real data against the noise-only simulation. Generated by '
      '`noise_rms_compare.py`.')
    A('')
    A('## Question')
    A('')
    A('Is the PDHD electronics-noise simulation consistent with data?')
    A('')
    A('## Inputs and method')
    A('')
    A('- **Data**: PDHD `run027409`, event 0 — raw pre-NF ADC frames '
      '(`protodunehd-orig-frames-anode{0-3}.tar.bz2`), all 4 APAs.')
    A('- **Simulation**: noise-only run of the production noise chain '
      '(`pdhd_sim/wct-sim-noise-only.jsonnet`): `EmpiricalNoiseModel` + '
      '`AddNoise` + `Digitizer`, configuration taken verbatim from '
      '`cfg/pgrapher/experiment/pdhd/sim.jsonnet`. FE gain 14 mV/fC — the '
      'run027409 gain, per `input_data/META.json` — selecting the '
      '`protodunehd-noise-spectra-14mVfC-v1.json.bz2` spectra file.')
    A('- **Noise RMS**: per channel, the WireCell sigproc '
      '`Derivations::CalcRMS` 4.5σ clip (`sigproc/src/Derivations.cxx`), '
      'iterated to convergence so signal samples are excluded, then the '
      'population RMS of the rest. Measured on the raw ADC waveform, before '
      'noise filtering.')
    A('')
    A('## Result — the simulation UNDER-predicts the data noise')
    A('')
    A('Median noise RMS over all channels of each APA / plane (ADC counts, '
      'and the voltage equivalent at %.1f µV/count):' % LSB_UV)
    A('')
    A('| APA | plane | data [ADC] | sim [ADC] | sim/data | data [mV] | sim [mV] |')
    A('|----:|-------|-----------:|----------:|---------:|----------:|---------:|')
    for n, pl, d, s in rows:
        A('| %d | %s | %.2f | %.2f | %.2f | %.3f | %.3f |'
          % (n, pl, d, s, s / d, d * LSB_UV / 1e3, s * LSB_UV / 1e3))
    A('')
    A('Three observations:')
    A('')
    A('1. **The simulation under-predicts the data on every APA and plane**, '
      'with sim/data ≈ %.2f–%.2f. The simulated noise is too low.'
      % (min(ratios), max(ratios)))
    A('2. **The simulation is APA-uniform; the data is not.** The sim produces '
      'essentially the same RMS on all four APAs (≈13.6 / 13.7 / 10.7 ADC for '
      'U / V / W) because one spectra file and a uniform ADC config feed every '
      'APA. The data instead splits cleanly by **even/odd APA** — APA0 and '
      'APA2 (U/V ≈ 20 ADC) vs APA1 and APA3 (U/V ≈ 16.5 ADC). Even and odd '
      'APAs sit on opposite drift sides (`sign = 2*(n%2)-1` in '
      '`params.jsonnet`), so this is a **drift-side noise asymmetry** — and, '
      'driven by a single APA-uniform spectra file, one the simulation is '
      'structurally unable to reproduce.')
    A('3. **The plane ordering is qualitatively right.** W (collection) is '
      'quieter than U/V in both data and simulation.')
    A('')
    A('### Contributing factor: no coherent noise in the simulation')
    A('')
    A('The PDHD sim adds noise with `AddNoise` (`IncoherentAddNoise`) only — '
      'there is no `CoherentAddNoise` and no `GroupNoiseModel` in '
      '`sim.jsonnet`. Real data noise is incoherent + coherent. The missing '
      'coherent component makes the simulation lower than data, consistent '
      'with the across-the-board under-prediction seen here; the incoherent '
      'spectra file itself also appears somewhat under-tuned.')
    A('')
    A('## Per-APA comparison')
    A('')
    for n in range(NANODE):
        A('### APA %d' % n)
        A('')
        A('![APA %d](noise_rms/noise_rms_compare_anode%d.png)' % (n, n))
        A('')
    A('## Summary across APAs')
    A('')
    A('![summary](noise_rms/noise_rms_compare_summary.png)')
    A('')
    A('Per-source overviews (all 4 APAs overlaid):')
    A('')
    A('![data](noise_rms/noise_rms_data_summary.png)')
    A('')
    A('![sim](noise_rms/noise_rms_sim_summary.png)')
    A('')
    A('## Caveats')
    A('')
    A('- **Residual signal in data**: event 0 is a real triggered event with '
      'higher channel occupancy than the PDVD event used in the sister study. '
      'A single 4.5σ clip pass over-reads the busier APAs by up to ~25%, so '
      'the clip is iterated to convergence; the converged result agrees with '
      'an independent percentile-based RMS to within a few percent.')
    A('- **APA0 V-plane**: a known APA0 V-plane anomaly affects signal/decon '
      'behaviour elsewhere; it does not show up in the raw noise RMS here — '
      'APA0 V sits with APA2 V, both in the noisier pair.')
    A('- **Tick period**: data is 512 ns/tick (native, pre-resampler), sim is '
      '500 ns/tick. This is a sub-1% effect on ADC-count RMS and is not '
      'corrected.')
    A('- The simulation was run with `nticks = 6000`; data frames have 5859 '
      'ticks — ample statistics for a per-channel RMS in both cases.')
    A('')
    A('## Conclusion')
    A('')
    A('The PDHD electronics-noise simulation does **not** reproduce the data. '
      'It under-predicts the per-channel noise RMS by roughly 20-35%, and -- '
      'because it drives every APA from a single noise-spectra file — it '
      'cannot reproduce the real drift-side noise asymmetry (even APAs 0/2 '
      'noisier than odd APAs 1/3). Re-tuning the incoherent noise spectra '
      '(`protodunehd-noise-spectra-14mVfC-v1.json.bz2`) and adding a coherent '
      'noise component would be needed to match data. See '
      '`pdhd_noise_simulation.md` for how the noise model is built.')
    A('')

    out = os.path.join(SCRIPTDIR, 'noise_rms_comparison.md')
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines))
    print('  wrote %s' % out)


def main():
    data, sim = load('data'), load('sim')
    print('=== data vs sim comparison ===')
    for n in range(NANODE):
        plot_anode(n, data, sim)
    plot_summary(data, sim)
    write_md(data, sim)
    print('done.')


if __name__ == '__main__':
    main()
