#!/usr/bin/env python3
"""
Compare PDHD per-channel electronics-noise RMS: data vs. noise-only simulation.

Reads noise_rms_data.npz and noise_rms_sim.npz (produced by noise_rms.py),
overlays data and simulation RMS-vs-channel for every APA / plane, builds a
summary figure, and writes the comparison report noise_rms_comparison.md.

Run noise_rms.py --source data and --source sim first.

Usage:  ./noise_rms_compare.py
"""
import os

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(SCRIPTDIR, 'noise_rms')

PLANES = ['U', 'V', 'W']
NANODE = 4

# Digitizer LSB (V/count), from cfg/pgrapher/experiment/pdhd/params.jsonnet:
#   resolution = 14 bits -> 2**14 = 16384 counts
#   fullscale [0.2, 1.6] V -> span 1.4 V   (uniform across all 4 APAs)
LSB_UV = 1.4 / 16384 * 1e6   # microvolt/count

# Pre-NF data medians [ADC], from the earlier raw-frame study (commit 63bee27).
# Kept here so the report can show, side by side, how much each APA / plane
# lost to noise filtering -- the asymmetric drop is the coherent-noise
# fingerprint and the headline of the post-NF comparison.
PRE_NF = {
    (0, 'U'): 19.82, (0, 'V'): 20.24, (0, 'W'): 15.32,
    (1, 'U'): 16.37, (1, 'V'): 16.49, (1, 'W'): 12.75,
    (2, 'U'): 20.10, (2, 'V'): 20.90, (2, 'W'): 15.50,
    (3, 'U'): 16.42, (3, 'V'): 16.76, (3, 'W'): 12.90,
}


def load(src):
    return dict(np.load(os.path.join(OUTDIR, 'noise_rms_%s.npz' % src)))


def plot_anode(n, data, sim):
    fig, axes = plt.subplots(3, 1, figsize=(11, 9))
    fig.suptitle('PDHD noise RMS: post-NF data vs. simulation  --  APA %d' % n,
                 fontsize=12)
    for ax, pl in zip(axes, PLANES):
        d = data['anode%d_%s_rms' % (n, pl)]
        s = sim['anode%d_%s_rms' % (n, pl)]
        ax.plot(np.arange(len(d)), d, lw=0.8, color='C0',
                label='data (post-NF)  median = %.2f ADC' % np.median(d))
        ax.plot(np.arange(len(s)), s, lw=0.8, color='C1',
                label='sim (raw)       median = %.2f ADC' % np.median(s))
        ax.set_ylabel('noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xlim(0, max(len(d), len(s)) - 1)
        ax.set_ylim(0, max(np.percentile(d, 99), np.percentile(s, 99)) * 1.35)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, loc='upper right')
    axes[-1].set_xlabel('channel index within plane')
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_anode%d.png' % n)
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def plot_summary(data, sim):
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.suptitle('PDHD noise RMS: post-NF data vs. simulation  --  per-APA median',
                 fontsize=12)
    x = np.arange(NANODE)
    for ax, pl in zip(axes, PLANES):
        dmed = [np.median(data['anode%d_%s_rms' % (n, pl)]) for n in x]
        smed = [np.median(sim['anode%d_%s_rms' % (n, pl)]) for n in x]
        ax.plot(x, dmed, 'o-', color='C0', label='data (post-NF)')
        ax.plot(x, smed, 's--', color='C1', label='sim (raw)')
        ax.set_xlabel('APA')
        ax.set_ylabel('median noise RMS [ADC]')
        ax.set_title('%s plane' % pl, fontsize=10)
        ax.set_xticks(x)
        ax.set_ylim(0, None)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9)
    plt.tight_layout()
    out = os.path.join(OUTDIR, 'noise_rms_compare_summary.png')
    plt.savefig(out, dpi=130)
    plt.close()
    print('  wrote %s' % out)


def med(arrs, n, pl):
    return float(np.median(arrs['anode%d_%s_rms' % (n, pl)]))


def write_md(data, sim):
    # per-APA / per-plane medians
    rows = [(n, pl, med(data, n, pl), med(sim, n, pl)) for n in range(NANODE)
            for pl in PLANES]
    ratios = [s / d for _, _, d, s in rows]

    lines = []
    A = lines.append
    A('# PDHD electronics noise: data vs. simulation')
    A('')
    A('Per-channel electronics-noise RMS for ProtoDUNE Horizontal Drift, '
      'comparing the real **post-noise-filtering** data waveform against the '
      'noise-only simulation. Generated by `noise_rms_compare.py`.')
    A('')
    A('## Question')
    A('')
    A('Is the PDHD electronics-noise simulation consistent with data?')
    A('')
    A('## Inputs and method')
    A('')
    A('- **Data**: PDHD `run027409`, event 0 — the **post-NF** waveform '
      '(`protodunehd-sp-frames-raw-anode{0-3}.tar.bz2`, frame tag `raw<N>`): '
      'the output of the noise-filtering chain (`wct-nf-sp.jsonnet`), tapped '
      'immediately after NF and before signal processing. All 4 APAs.')
    A('- **Simulation**: noise-only run of the production noise chain '
      '(`pdhd_sim/wct-sim-noise-only.jsonnet`): `EmpiricalNoiseModel` + '
      '`AddNoise` + `Digitizer`, configuration taken verbatim from '
      '`cfg/pgrapher/experiment/pdhd/sim.jsonnet`. FE gain 14 mV/fC — the '
      'run027409 gain, per `input_data/META.json`, selecting the '
      '`protodunehd-noise-spectra-14mVfC-v1.json.bz2` spectra file. The sim '
      'frame is the raw digitized noise — it is **not** noise-filtered.')
    A('- **Why post-NF data vs. raw sim**: the simulation generates only '
      '*incoherent* electronics noise (see "no coherent noise" below). Real '
      'raw data carries incoherent + coherent noise; NF removes the coherent '
      'part. The post-NF data waveform is therefore the incoherent-dominated '
      'noise that the simulation actually models — the intended like-for-like '
      'comparison. Caveat: NF also slightly attenuates the incoherent noise '
      'it keeps (group-median subtraction), by an estimated few percent, '
      'which the raw sim has not undergone — so the sim/data ratios below are '
      'biased a few percent high relative to a strict post-NF-vs-post-NF test.')
    A('- **Noise RMS**: per channel, the WireCell sigproc '
      '`Derivations::CalcRMS` 4.5σ clip (`sigproc/src/Derivations.cxx`), '
      'iterated to convergence so signal samples are excluded, then the '
      'population RMS of the rest.')
    A('')
    A('> This supersedes the earlier pre-NF comparison (commit `63bee27`, '
      'which measured the raw `protodunehd-orig-frames`). Moving the data '
      'side to the post-NF waveform changes the conclusion substantially — '
      'see observation 2.')
    A('')
    A('## Result — on the post-NF (incoherent) footing the simulation is broadly consistent with data')
    A('')
    A('Median noise RMS over all channels of each APA / plane (ADC counts, '
      'and the voltage equivalent at %.1f µV/count):' % LSB_UV)
    A('')
    A('| APA | plane | data [ADC] | sim [ADC] | sim/data | data [mV] | sim [mV] |')
    A('|----:|-------|-----------:|----------:|---------:|----------:|---------:|')
    for n, pl, d, s in rows:
        A('| %d | %s | %.2f | %.2f | %.2f | %.3f | %.3f |'
          % (n, pl, d, s, s / d, d * LSB_UV / 1e3, s * LSB_UV / 1e3))
    A('')
    A('Three observations:')
    A('')
    A('1. **The simulation tracks the data closely**, with sim/data ≈ '
      '%.2f–%.2f — it sits a few percent low. This is a large improvement '
      'over the pre-NF comparison (sim/data ≈ 0.66–0.84): most of the '
      'apparent pre-NF discrepancy was coherent noise, which the simulation '
      'does not generate and NF removes from data.'
      % (min(ratios), max(ratios)))
    A('2. **The pre-NF "drift-side asymmetry" was coherent noise.** Pre-NF '
      '(commit `63bee27`) the data split sharply by even/odd APA — APA0 and '
      'APA2 (U/V ≈ 20 ADC) much louder than APA1 and APA3 (U/V ≈ 16.5) — and '
      'because even/odd APAs sit on opposite drift sides this looked like a '
      'drift-side noise asymmetry that the APA-uniform simulation could never '
      'reproduce. **Post-NF the asymmetry is gone**: all four APAs cluster at '
      '14.1–15.0 ADC (U/V), a few-percent residual that even slightly '
      'reverses. NF removes *coherent* noise, so the pre-NF asymmetry was '
      'coherent — and the simulation being APA-uniform is not a defect, '
      'because the post-NF data is APA-uniform too. The pre→post change is '
      'sharply asymmetric, which is the whole story:')
    A('')
    A('| APA | plane | pre-NF data [ADC] | post-NF data [ADC] | removed by NF |')
    A('|----:|-------|------------------:|-------------------:|--------------:|')
    for n in range(NANODE):
        for pl in PLANES:
            pre = PRE_NF[(n, pl)]
            post = med(data, n, pl)
            A('| %d | %s | %.2f | %.2f | %.2f |' % (n, pl, pre, post, pre - post))
    A('')
    A('   APA0 and APA2 lose ~4–7 ADC to NF, APA1 and APA3 only ~1.2–1.8 — '
      'the coherent noise was concentrated on the even-numbered APAs (one '
      'drift side).')
    A('3. **Plane ordering is right; a small W residual remains.** W '
      '(collection) is quieter than U/V in both data and simulation. Post-NF '
      'data W ≈ 11.4–11.6 ADC vs sim ≈ 10.7 — a ~6–8% under-prediction, the '
      'same direction and size as the U/V gap.')
    A('')
    A('### No coherent noise in the simulation — by design, the right thing here')
    A('')
    A('The PDHD sim adds noise with `AddNoise` (`IncoherentAddNoise`) only — '
      'there is no `CoherentAddNoise` and no `GroupNoiseModel` in '
      '`sim.jsonnet`. Against **post-NF** data that is the correct comparison, '
      'and is why the agreement above is good. Against **raw** data it is '
      'not: raw data still carries its coherent component, so a raw sim '
      'under-predicts raw data by the coherent fraction — which for PDHD is '
      'large (the drift-side asymmetry of observation 2). Reproducing raw '
      'data would require adding a coherent-noise component to the '
      'simulation.')
    A('')
    A('## Per-APA comparison')
    A('')
    for n in range(NANODE):
        A('### APA %d' % n)
        A('')
        A('![APA %d](noise_rms/noise_rms_compare_anode%d.png)' % (n, n))
        A('')
    A('## Summary across APAs')
    A('')
    A('![summary](noise_rms/noise_rms_compare_summary.png)')
    A('')
    A('Per-source overviews (all 4 APAs overlaid):')
    A('')
    A('![data](noise_rms/noise_rms_data_summary.png)')
    A('')
    A('![sim](noise_rms/noise_rms_sim_summary.png)')
    A('')
    A('## Caveats')
    A('')
    A('- **Comparison footing**: post-NF data vs. raw (un-filtered) sim. NF '
      'removes coherent noise — which the sim never generates — but also '
      'attenuates the surviving incoherent noise by an estimated few percent; '
      'the raw sim has not been through NF, so sim/data here is biased a few '
      'percent high. A strict test would run the sim through the same NF '
      'chain.')
    A('- **Bad channels**: NF zeroes channels it flags bad; in this event '
      'that is ≤10 channels per APA / plane (≈1%), appearing as RMS = 0. The '
      'medians quoted here are unaffected.')
    A('- **Residual signal in data**: event 0 is a real triggered event; the '
      '4.5σ clip is iterated to convergence so signal samples are excluded, '
      'and the converged result agrees with an independent percentile-based '
      'RMS to within a few percent.')
    A('- **APA0 V-plane**: a known APA0 V-plane anomaly affects signal/decon '
      'behaviour elsewhere; it does not stand out in the post-NF noise RMS '
      'here.')
    A('- **Tick period**: the post-NF data has been resampled to 500 ns/tick '
      'by the NF chain (raw data is 512 ns); the simulation is natively '
      '500 ns/tick — the two now match. Post-NF data frames have 5999 ticks, '
      'the sim 6000 — ample statistics for a per-channel RMS.')
    A('')
    A('## Conclusion')
    A('')
    A('On the post-NF / incoherent-noise footing — which is what the '
      'simulation actually models — the PDHD electronics-noise simulation is '
      '**broadly consistent with data**: it reproduces the per-channel noise '
      'RMS to within ~10% (sim/data ≈ 0.90–0.97, a few percent low) and '
      'correctly produces an APA-uniform noise field. The large discrepancy '
      'reported in the earlier '
      'pre-NF study was dominated by **coherent** noise — NF removes it from '
      'data and the simulation never generates it. Two follow-ups would close '
      'the remaining gap: a few-percent upward retune of the incoherent '
      'spectra file `protodunehd-noise-spectra-14mVfC-v1.json.bz2`, and — if '
      'agreement with *raw* data is wanted — adding a coherent-noise '
      'component. See `pdhd_noise_simulation.md` for how the noise model is '
      'built.')
    A('')

    out = os.path.join(SCRIPTDIR, 'noise_rms_comparison.md')
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines))
    print('  wrote %s' % out)


def main():
    data, sim = load('data'), load('sim')
    print('=== data vs sim comparison ===')
    for n in range(NANODE):
        plot_anode(n, data, sim)
    plot_summary(data, sim)
    write_md(data, sim)
    print('done.')


if __name__ == '__main__':
    main()
