#!/usr/bin/env python3
"""The owner's review queue, in priority tiers.

    mkqueue.py RECORD KEY [KEY_EXTRAS] [--shots DIR] > queue.md

doc pdhd/18.  Ported from the doc pdvd/55 tranche-2 scratch mkqueue.py.  That one
listed every row with any reason in one table; on PDHD (164 medium calls) that
queued 232 of 317 items, which is not a queue.  So the rows are sorted into tiers,
most informative first, and each item appears once, in its highest tier:

  A  the blind calibration disagrees with the owner's own smx1 label
  B  the scanner moved the stop (pin_rr) or read an undershoot (the stop point)
  C  a hand stopper whose fit end is the UPPER end of the track (a stop there
     needs an upward-going particle; the rubric has no direction test)
  D  a HIGH-confidence scan call that disagrees with bare production's is_stm
  E  a LOW-confidence call
  F  a MEDIUM-confidence call that disagrees with production's is_stm
  G  everything else worth a look: UNCLEAR / MESSY, the cap-64 extras, and the
     remaining medium calls -- listed by key only

The key is bare production (never the survey scan arm).
"""
import argparse, csv, json, os

ap = argparse.ArgumentParser()
ap.add_argument("record"); ap.add_argument("key"); ap.add_argument("key_extras", nargs="?")
ap.add_argument("--shots", default=None)
a = ap.parse_args()


def read_tsv(p):
    return list(csv.DictReader([l for l in open(p) if not l.startswith("#")], delimiter="\t"))


def base(v):
    return v[5:] if v and v.startswith("FRAG_") else v


def upper_end(k):
    if not a.shots:
        return False
    try:
        e = json.load(open(os.path.join(a.shots, k.replace("/", "_"), "context.json")))["ends"]
        return e["stop"]["xyz"][1] > e["entry"]["xyz"][1]
    except Exception:
        return False


rec = json.load(open(a.record))
K = {"%s/%s" % (r["event"], r["cluster"]): dict(r, src="prod") for r in read_tsv(a.key)}
if a.key_extras:
    for r in read_tsv(a.key_extras):
        K.setdefault("%s/%s" % (r["event"], r["cluster"]), dict(r, src="cap64"))

TIERS = {"A": "the blind calibration disagrees with the owner's smx1 label",
         "B": "the scanner moved the stop, or read an undershoot",
         "C": "a stopper whose fit end is the upper end of the track (needs an upward-going particle)",
         "D": "a high-confidence scan call against production's is_stm",
         "E": "a low-confidence call",
         "F": "a medium-confidence call against production's is_stm",
         "G": "UNCLEAR / MESSY, cap-64 extras, other medium calls"}
rows = {t: [] for t in TIERS}
for r in rec:
    k = r["key"]; kk = K[k]; v = base(r["verdict"]); n = r.get("notes") or ""
    stop = v in ("STM_MICHEL", "STM_ONLY"); cs = int(kk["is_stm"]) == 1
    against = (v not in ("MESSY", "UNCLEAR")) and (stop != cs)
    why = []
    if against:
        why.append("scan STM, chain not" if stop else "chain STM, scan not")
    if r.get("pin_rr") is not None:
        why.append("PIN r%.1f" % r["pin_rr"])
    for pfx in ("UNDERSHOOT", "FLAT_STOP", "NO_MEASUREMENT", "ANODE", "SEAM", "CATHODE", "ISOCHRONOUS"):
        if pfx + ":" in n:
            why.append(pfx)
    if kk["src"] == "cap64":
        why.append("CAP-64 extra")
    if r.get("owner_smx1"):
        ov = base(r["owner_smx1"].get("choice") or r["owner_smx1"].get("label"))
        if ov != v:
            rows["A"].append((r, ["blind %s vs owner %s" % (v, ov)] + why))
        continue
    if r.get("pin_rr") is not None or "UNDERSHOOT:" in n:
        t = "B"
    elif stop and upper_end(k):
        t = "C"
    elif against and r["confidence"] == "high":
        t = "D"
    elif r["confidence"] == "low":
        t = "E"
    elif against and r["confidence"] == "medium":
        t = "F"
    elif v in ("MESSY", "UNCLEAR") or kk["src"] == "cap64" or r["confidence"] == "medium":
        t = "G"
    else:
        continue
    rows[t].append((r, why))

nq = sum(len(v) for v in rows.values())
print("# PDHD STM + Michel hand scan (smx18) — the owner's review queue\n")
print("Generated by `pdhd/stm_michel_scan/campaign/mkqueue.py` from the committed record "
      "(doc pdhd/18). %d of %d items are queued, in tiers, most informative first; each item "
      "appears once. The chain is bare PDHD production (`p82bhoff`; `h18b` for the cap-64 "
      "extras). Not listed: high-confidence calls that agree with the chain and carry no pin.\n"
      % (nq, len(rec)))
for t, desc in TIERS.items():
    L = sorted(rows[t], key=lambda x: x[0]["scan_id"])
    print("## %s — %s (%d)\n" % (t, desc, len(L)))
    if not L:
        print("none\n")
        continue
    if t == "G":
        print(", ".join("`%s` %s/%s" % (r["key"], r["verdict"], r["confidence"][0]) for r, _ in L) + "\n")
        continue
    print("| scan | item | verdict | kind | conf | why |")
    print("|---:|---|---|---|---|---|")
    for r, why in L:
        print("| %d | `%s` | %s | %s | %s | %s |" % (r["scan_id"], r["key"], r["verdict"],
                                                    r["michel_kind"], r["confidence"], "; ".join(why)))
    print()
